### ISSUE TITLE
State from scope with in query

### ISSUE THREAD

**Issue by denzelem** [makandra/rails_state_machine#3]
Maybe related to https://github.com/makandra/rails_state_machine/issues/1.

```
class User < ActiveRecord::Base
  state_machine do
    state :draft, initial: true
    state :active
    state :archived
  end

  validates :email, presence: true, unless: -> { draft? }
end
```

```
user = User.where(state: ['draft', 'active'].new
user.state #=> "['draft', 'active']"
user.save! #=> ActiveRecord::RecordInvalid: Validation failed: Email can't be blank
user.state #=> nil
```

The state should never be `nil`. Also we should think about a solution to handle in query scopes.

**Comment by triskweline** [comment]
OK but that can never work: `User.where(state: ARRAY).new`

You can never call `new` and `build` on a scope unless all `where` attributes are flat, scalar values.

In the same vein we cannot expect `User.where('age >= 18').new.age` to be any reasonable number.

**Comment by triskweline** [comment]
We already have logic that correctly gets the state for unsaved records: https://github.com/makandra/rails_state_machine/blob/0d30e61b5216e53d18721a47d7e2199f8343f869/lib/rails_state_machine/state_machine.rb#L160

**Comment by denzelem** [comment]
That makes sense, I'm a little bit unhappy, that the state machine does not complain when a wrong state is set.

I will close this and we will try to figure out in https://github.com/makandra/rails_state_machine/issues/1 if it makes sense to raise for an invalid state. Thanks @triskweline!
