### ISSUE TITLE
Misleading error message when referring to a missing state

### ISSUE THREAD

**Issue by kratob** [makandra/rails_state_machine#7]
When accidentally using a wrong state like this

```
state_machine do
  state :start
  state :end
  event :finish do
    transitions from: :beginning, to: :end  # should be :start
  end
end
```
the user will get an error like
```
NoMethodError:
       undefined method `model' for #<RailsStateMachine::StateMachine:0x00005586e193d2e0>
```
The culprit seems to be this line: https://github.com/makandra/rails_state_machine/blob/72489075461673f8df8c6ffcb8e34f29e4a23538/lib/rails_state_machine/event.rb#L80

**Comment by makmic** [comment]
This issue was already resolved in 4797eda7208d5037d819576a65ff2bd859525435, I'm closing it after adding some specs.
